image_jpeg: '9'
image_png: '9'
application_pdf: '17'
application_vnd_ms-excel: '8'
application_xml: '8'
text_plain: '17'
video_mp4: '11'
audio_mpeg: '14'
image_tiff: '9'
application_octet-stream: '9'
video_quicktime: '11'
application_msaccess: '8'
application_vnd_openxmlformats-officedocument_spreadsheetml_sheet: '8'
audio_x-wav: '14'
video_x-m4v: '11'
application_vnd_openxmlformats-officedocument_wordprocessingml_document: '17'
audio_x-ms-wma: '14'
'text_html; charset=UTF-8': ''
video_mpeg: '11'
