islandora_bagger_mode: remote
islandora_bagger_default_config_file_path: /var/www/html/private/bagger_config/islandora_bagger_config.yml
islandora_bagger_rest_endpoint: 'http://localhost:8000/api/createbag'
islandora_bagger_add_email_user: 0
islandora_bagger_local_bagger_directory: /var/www/html/islandora_bagger
