repo_bento_search:
  legacy_repository_api_url: 'https://repo-dev.lib.asu.edu/api/items/search'
  dataverse_api_url: 'https://dataverse-test.lib.asu.edu/api/search'
  num_results: 5
_core:
  default_config_hash: qWXUrFSkCM6T-XsrOldlHqWXFXazbsly1xkB3ZvBdLU
legacy_repository_api_url: 'https://repository.asu.edu/api/items/search'
dataverse_api_url: 'https://dataverse.asu.edu/api/search'
legacy_repository_api_key: ''
num_results: '5'
titles_this_site: KEEP
titles_legacy_repo: 'Legacy Repository'
titles_dataverse: 'ASU Research Data Repository'
this_i8_api_url: 'https://keep.lib.asu.edu/api/search'
second_i8_api_url: 'https://prism.lib.asu.edu/api/search'
titles_this_i8: KEEP
titles_second_i8: PRISM
recent_items_api: 'https://keep.lib.asu.edu/api/recent'
dataverse_tooltip: ''
legacy_repo_tooltip: ''
this_i8_tooltip: ''
second_i8_tooltip: ''
