smtp_on: true
smtp_host: email-smtp.us-west-2.amazonaws.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_autotls: true
smtp_timeout: 30
smtp_username: AKIASBVQ3ZQ45UVYJ7HE
smtp_password: BOlDpwQ1W7m6XOUFyRPAZRV+kVqug68KEW8M0mBREfEJ
smtp_from: digitalrepository@asu.edu
smtp_fromname: 'ASU Digital Repository'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
smtp_keepalive: false
