broker_url: 'tcp://activemq:61613'
jwt_expiry: '+1 week'
gemini_pseudo_bundles:
  'asu_repository_item:node': 'asu_repository_item:node'
  'collection:node': 'collection:node'
  'islandora_object:node': 'islandora_object:node'
  'audio:media': 'audio:media'
  'file:media': 'file:media'
  'image:media': 'image:media'
  'video:media': 'video:media'
